// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"lantak/config"
	"lantak/internal/controller"
	"lantak/internal/infra/nats"
	"lantak/internal/service"
)

// Injectors from wire.go:

func InitChatController(cfg config.Config) *controller.ChatController {
	conn := nats.NewNats(cfg)
	messageService := service.NewMessageService(conn)
	chatController := controller.NewChatController(messageService)
	return chatController
}
